Test and Hinglish Classification
NirantK/kavita pull request #4
Opened 2020-11-02 14:26 UTC by meghanabhange

2020-11-03 04:04 UTC, NirantK requested changes

2020-11-03 04:04 UTC, NirantK commented on Alfaaz.py
> +import logging
Use isort and black please!

2020-11-03 04:04 UTC, NirantK commented on Alfaaz.py
>      except:
Catch specific `Exception` and errors please?

2020-11-03 04:04 UTC, NirantK commented on Alfaaz.py
> +        st.error("Invalid tweet, please try again")
This needs to be more descriptive than "Invalid Tweet". Maybe something like invalid twitter hash, auth failure, tweepy error or more.

2020-11-03 04:04 UTC, NirantK commented on Alfaaz.py
>          tweet = twitter_API.get_status(tweet_id[0]).text
I am guessing we should use 280 char, `full_text` field instead of `text`?

2020-11-03 04:04 UTC, NirantK commented on test.py
> +class TestHinglishSentiement(unittest.TestCase):
Maybe have 2-3 tweets per sentiment as test cases?

2020-11-12 09:58 UTC, meghanabhange commented on Alfaaz.py
> +import logging
Did, I sort puts logging first :(

2020-11-12 10:00 UTC, meghanabhange commented on Alfaaz.py
>      except:
I thought using `logger.exception` was helping that. 
`logger.exception` logs levels at the `error` level and automagically adds the exception that caused it go in the except loop.

2020-11-12 16:46 UTC, NirantK commented
@meghanabhange please resolve merge conflicts?

2020-12-29 08:47 UTC, closed without merging

2020-12-29 08:47 UTC, meghanabhange commented
Closing this :(

2020-12-29 08:54 UTC, NirantK commented
What was this PR even about? Wow. We really need to treat with a little more respect @meghanabhange  :P